Lesson4/Lesson3/models/UserRegistration/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
   
    path('register/', views.register_root, name='users'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
   
    
]

Lesson4/Lesson3/models/models/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('user/', include('UserRegistration.urls'))
    
]

#urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

Lesson4/Lesson3/models/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
   
    path('', views.post_list, name='lists'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
    
]

Lesson4/Lesson3/models/UserRegistration/models.py
from django.db import models

# Create your models here.

Lesson4/Lesson3/models/models/asgi.py
"""
ASGI config for models project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "models.settings")

application = get_asgi_application()

Lesson4/Lesson3/models/models/settings.py
"""
Django settings for models project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8riqgu-k$)p*rlte%0$nt^@7q41h2lbp%aur*_(8m8(u0g0wof"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'posts',
    'UserRegistration'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "models.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "models.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = 'media/'
STATIC_ROOT = BASE_DIR / 'assests'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS =[
    BASE_DIR / 'static'
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

Lesson4/Lesson3/models/models/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

Lesson4/Lesson3/models/models/wsgi.py
"""
WSGI config for models project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "models.settings")

application = get_wsgi_application()

Lesson4/Lesson3/models/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default="fallback.png", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    def __str__(self):
        return self.title

Lesson4/Lesson3/models/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'banner']

Lesson4/Lesson3/models/UserRegistration/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout

# Create your views here.
def register_root(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("posts:lists")
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get(next))
            return redirect('posts:lists')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def logout(request):
    if request.method == "POST":
        auth_logout(request)
        return redirect('posts:lists')

Lesson4/Lesson3/models/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

@login_required(login_url='/user/login/')
def post_new(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            # save with user
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect("posts:lists")

    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

Lesson4/Lesson3/models/UserRegistration/templates/users/login.html
{% extends  "layout.html"%}

{% block title %}
Login User
{% endblock  %}

{% block content %}
<article>
   <h1>Login User</h1>
   <form class="form-with-validation" action="{%url 'users:login'%}" method="post">
      {% csrf_token %}
      {{form}}
      {% if request.POST.next %}
      <input type="hidden" name='text' value='{{request.POST.next}}'>
      {% endif %}
      <button class='form-submit'>Submit</button>
   </form>
</article>
{% endblock  %}

Lesson4/Lesson3/models/UserRegistration/templates/users/register.html
{% extends  "layout.html"%}

{% block title %}
Resiter A New User
{% endblock  %}

{% block content %}
<article>
   <h1>Register a New User</h1>
   <form class="form-with-validation" action="{%url 'users:register'%}" method="post">
      {% csrf_token %}
      {{form}}
      <button class='form-submit'>Submit</button>
   </form>
</article>
{% endblock  %}

Lesson4/Lesson3/models/posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}
New Post
{% endblock  %}

{% block  content%}
<section>
   <h1>New Post</h1>
   <form class='form-with-validation' action="{% url 'posts:new-post' %}" method='POST', enctyoe='multipart/form-data'>
   {% csrf_token %}
   {{form}}
   <button class='form-submit'>Add Post</button>
</form>
</section>

   
{% endblock  %}

Lesson4/Lesson3/models/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
{{post.title}}
{% endblock  %}

{% block  content%}
<section>
    <h1>{{post.title}}</h1>
  
    <article class='posts'> 
        <img class="banner" src="{{post.banner.url}}" alt="{{post.title}}">
        <a href="{% url "posts:lists"%}"><p>Return Back</p></a>
        <p>{{ post.date }}</p>
        <p>{{ post.body}}</p>

    </article>



</section>

   
{% endblock  %}

Lesson4/Lesson3/models/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}
{% block title %}
Post
{% endblock %}

{% block  content%}
<section>
    <h1>Post</h1>
    {% for post in posts%}
    <article class='posts'> 
        <a href="{% url "posts:page" slug=post.slug %}"><h2>{{ post.title }}</h2></a>
        <p>{{ post.date }} by {{post.author}}</p>
        <p>{{ post.body}}</p>

    </article>

    {% endfor %}

</section>

   
{% endblock  %}

Lesson4/Lesson3/models/templates/about.html
{% extends 'layout.html' %}
{% block title %}
About page
{% endblock %}

{% block  content%}
<h1>About</h1>
    <p>This is <a href="/">Home</a> page.</p>
{% endblock  %}

Lesson4/Lesson3/models/templates/home.html
 {% extends "layout.html" %}

{% block title %}
Home Page
{% endblock  %}
{% block content %}
<h1>Home</h1>
<p>This is <a href="/about">About</a> page.</p>
{% endblock  %}

Lesson4/Lesson3/models/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>
        {% block title %}
        Django App!
         {% endblock %}
    </title>
</head>
<body>
    <nav>
        <a href="/"><span role='img' aria-label='Home'>🏚️</span></a> |
        <a href="/about"><span role='img' aria-label='About'>😉</span></a> |
        <a href=" {% url "posts:lists" %} "><span role='img' aria-label='Posts'>📰</span></a> |
        {% if user.is_authenticated %}
        <a href=" {% url "posts:new-post" %} "><span role='img' aria-label='New Post'>🆕</span></a> | 

        <form  class='logout' action="{% url 'users:logout'%}" method='post'>
            {% csrf_token %}
            <button class='logout-button' aria-label='User Logout'>👋</button>
        </form>
        {%  else %}
        <a href=" {% url "users:users" %} "><span role='img' aria-label='Register'>🚀</span></a> |
        <a href=" {% url "users:login" %} "><span role='img' aria-label='Login'>🔐</span></a> 
        
        {% endif %}
    </nav>
    <main>
        {% block content%}
        
        {% endblock%}
    </main>
    
</body>
</html>